import ImageOne from "../assets/farmlandone.jpg";

import ImageOne2 from "../assets/farmlandtwo.jpg";
import ImageOne3 from "../assets/farmlandthree.jpg";
import ImageOne4 from "../assets/farmlandfour.jpg";
import ImageOne5 from "../assets/farmlandfive.jpg";
import ImageOne6 from "../assets/farmlandone.jpg";
import ImageOne7 from "../assets/farmlandtwo.jpg";

export const RecentSaleLands = [
  {
    id: 1,
    image: ImageOne,
    title: "Masere Land",
    slug: "masere-Land",
    size: "2.6 acres",
    price: "TZS 90,200/acres",
    location: "Capri Point",
    owner: "Boke",
    agent: "No",
    type: "Land",
    discount: "-2%",
  },
  {
    id: 2,
    image: ImageOne2,
    title: "Riongote Land",
    slug: "riongote-land",
    size: "3.6 acres",
    price: "TZS 60,000/acres",
    location: "Igoma",
    owner: "Chacha M",
    agent: "Yes",
    type: "Land",
    discount: "-6%",
  },
  {
    id: 3,
    image: ImageOne3,
    title: "Ndugu Manga",
    slug: "ndugu-manga",
    size: "4.1 acres",
    price: "TZS 50,968/acres",
    location: "Igoma",
    owner: "Tereria",
    agent: "No",
    type: "Land",
    discount: "-8%",
  },
  {
    id: 4,
    image: ImageOne4,
    title: "Steve Mkulima",
    slug: "steve-mkulima",
    size: "1.9 acres",
    price: "TZS 80,897/acres",
    location: "Nyegezi",
    owner: "Martin",
    agent: "No",
    type: "Land",
    discount: "-3%",
  },
  {
    id: 5,
    image: ImageOne5,
    title: "Teacher Mosoba",
    slug: "teacher-mosoba",
    size: "2.1 acres",
    price: "TZS 80,897/acres",
    location: "Mwanza CBD",
    owner: "Josephine Mosoba",
    agent: "Yes",
    type: "Land",
    discount: "-6%",
  },
  {
    id: 6,
    image: ImageOne6,
    title: "Agness Boke",
    slug: "agness-boke",
    size: "5.2 acres",
    price: "TZS 80,897/acres",
    location: "Buswelu",
    owner: "A.B. Marwa",
    agent: "No",
    type: "Land",
    discount: "-7%",
  },
  {
    id: 7,
    image: ImageOne7,
    title: "Ndugu Benja",
    slug: "ndugu-benja",
    size: "7.3 acres",
    price: "TZS 70,797/acres",
    location: "Nyegezi",
    owner: "Benja Mtatiro",
    agent: "Yes",
    type: "Land",
    discount: "-11%",
  },
];
