import houseOne from "../assets/just__launched.png";
import houseTwo from "../assets/runda__house__one.jpg";
import houseThree from "../assets/property_ilemela.jpg";
import houseFour from "../assets/one__house.png";

export const RentalHouses = [
  {
    id: 1,
    image: houseOne,
    title: "Carlos House",
    slug: "masere-plot",
    areasize: "20m x 40m",
    price: "TZS 550m",
    location: "Buswelu",
    owner: "Boke",
    agent: "No",
    type: "Stand Alone",
    discount: "-2%",
  },
  {
    id: 2,
    image: houseTwo,
    title: "Gachuma Suites",
    slug: "masere-plot",
    areasize: "20m x 40m",
    price: "TZS 650m",
    location: "Capri Point",
    owner: "Boke",
    agent: "No",
    type: "Mansionette",
    discount: "-2%",
  },
  {
    id: 3,
    image: houseThree,
    title: "Adarry Plaza",
    slug: "masere-plot",
    areasize: "20m x 40m",
    price: "TZS 900m",
    location: "Capri Point",
    owner: "Boke",
    agent: "No",
    type: "Suites",
    discount: "-2%",
  },
  {
    id: 4,
    image: houseFour,
    title: "Marwa Residence",
    slug: "masere-plot",
    areasize: "20m x 40m",
    price: "TZS 120m",
    location: "Capri Point",
    owner: "Boke",
    agent: "No",
    type: "Mansionette",
    discount: "-2%",
  },

  {
    id: 5,
    image: houseOne,
    title: "Carlos House",
    slug: "masere-plot",
    areasize: "20m x 40m",
    price: "TZS 550m",
    location: "Buswelu",
    owner: "Boke",
    agent: "No",
    type: "Stand Alone",
    discount: "-2%",
  },
  {
    id: 6,
    image: houseTwo,
    title: "Gachuma Suites",
    slug: "masere-plot",
    areasize: "20m x 40m",
    price: "TZS 650m",
    location: "Capri Point",
    owner: "Boke",
    agent: "No",
    type: "Mansionette",
    discount: "-2%",
  },
  {
    id: 7,
    image: houseThree,
    title: "Adarry Plaza",
    slug: "masere-plot",
    areasize: "20m x 40m",
    price: "TZS 900m",
    location: "Capri Point",
    owner: "Boke",
    agent: "No",
    type: "Suites",
    discount: "-2%",
  },
  {
    id: 8,
    image: houseFour,
    title: "Marwa Residence",
    slug: "masere-plot",
    areasize: "20m x 40m",
    price: "TZS 120m",
    location: "Capri Point",
    owner: "Boke",
    agent: "No",
    type: "Mansionette",
    discount: "-2%",
  },
];
